name: Build and Upload Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: windows-latest  # or ubuntu-latest if cross-platform

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup CMake
        uses: lukka/get-cmake@v3.27.0

      - name: Configure project
        run: cmake -B build -S . -DCMAKE_BUILD_TYPE=Release

      - name: Build project
        run: cmake --build build --config Release

      - name: Upload artifact to release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            build/Release/testapp.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
